/*
 * This class is implemented to showw boosters of the game
 */
package cscrush;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author tendoushuu
 */
public class BoostersPanel extends javax.swing.JPanel {

    private Image robin;
    private Image halil;
    private Image eray;
    private Image ozcan;
    private Image william;
    private int pressedX,pressedY,pressedX1,pressedY1;
    private GamePlayScreenPanel parent;
    /**
     * Creates new form BoostersPanel
     * @param parent
     */
    public BoostersPanel(GamePlayScreenPanel parent) {
        initComponents();
        this.parent = parent;
        try {
            robin = ImageIO.read(getClass().getResource("/img/robin.jpg")).getScaledInstance(50, 50, Image.SCALE_DEFAULT);
            halil = ImageIO.read(getClass().getResource("/img/halil.jpg")).getScaledInstance(50, 50, Image.SCALE_DEFAULT);
            eray = ImageIO.read(getClass().getResource("/img/eray.jpg")).getScaledInstance(50, 50, Image.SCALE_DEFAULT);
            ozcan = ImageIO.read(getClass().getResource("/img/ozcan.jpg")).getScaledInstance(50, 50, Image.SCALE_DEFAULT);
            william = ImageIO.read(getClass().getResource("/img/william.jpg")).getScaledInstance(50, 50, Image.SCALE_DEFAULT);
             
        } catch (IOException ex) {
            Logger.getLogger(BoostersPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

/*
 * This method is implemented to showthe image of boosters
 * @param Graphics g  
 */
        @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        g.drawImage(eray,0,0,null);
        g.drawImage(robin,0,50,null);
        g.drawImage(halil,0,100,null);
        g.drawImage(ozcan,0,150,null);
        g.drawImage(william,0,200,null);
        
    }
/*
 * This method is implemented to get mouse clicks
 * @param java.awt.event.MouseEvent evt
 */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 0));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        int pressedX = evt.getX();
        int pressedY = evt.getY();
        if ( 0 <= pressedY && 50 >= pressedY) {
            int x1 = evt.getX();
            int x2 = evt.getX();
            int y1 = evt.getY();
            int y2 = evt.getY();
            parent.eray(x1,y1,x2,y2);
            System.err.println(x1+" "+y1+" "+x2+"  "+y2);
        }
        else if ( 50 <= pressedY && 99 >= pressedY ) {
            parent.altay();
        }
        else if ( 100<= pressedY && 149 >= pressedY ) {
            parent.altay();
        }
        else if ( 150 <= pressedY && 199 >= pressedY ) {
            parent.altay();
        }
        else if ( 200 <= pressedY && 249 >= pressedY ) {
           parent.altay();
        }
 
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
