/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cscrush;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author tendoushuu
 */
public class BoostersPanel extends javax.swing.JPanel {

    private Image robin;
    private Image halil;
    private Image eray;
    private Image ozcan;
    private Image william;
    /**
     * Creates new form BoostersPanel
     */
    public BoostersPanel() {
        initComponents();
        try {
            robin = ImageIO.read(new File("C:\\Users\\tendoushuu\\Documents\\1A.CSCrush\\project\\CSCRUSH\\src\\cscrush\\robin.jpg")).getScaledInstance(50, 50, Image.SCALE_DEFAULT);
            halil = ImageIO.read(new File("C:\\Users\\tendoushuu\\Documents\\1A.CSCrush\\project\\CSCRUSH\\src\\cscrush\\halil.jpg")).getScaledInstance(50, 50, Image.SCALE_DEFAULT);
            eray = ImageIO.read(new File("C:\\Users\\tendoushuu\\Documents\\1A.CSCrush\\project\\CSCRUSH\\src\\cscrush\\eray.jpg")).getScaledInstance(50, 50, Image.SCALE_DEFAULT);
            ozcan = ImageIO.read(new File("C:\\Users\\tendoushuu\\Documents\\1A.CSCrush\\project\\CSCRUSH\\src\\cscrush\\ozcan.jpg")).getScaledInstance(50, 50, Image.SCALE_DEFAULT);
            william = ImageIO.read(new File("C:\\Users\\tendoushuu\\Documents\\1A.CSCrush\\project\\CSCRUSH\\src\\cscrush\\william.jpg")).getScaledInstance(50, 50, Image.SCALE_DEFAULT);
             
        } catch (IOException ex) {
            Logger.getLogger(BoostersPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

        @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        g.drawImage(eray,0,0,null);
        g.drawImage(robin,0,50,null);
        g.drawImage(halil,0,100,null);
        g.drawImage(ozcan,0,150,null);
        g.drawImage(william,0,200,null);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
