/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cscrush;

/**
 *
 * @author berka
 */
public class CreditsPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreditsPanel
     */
    public CreditsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditBack = new javax.swing.JButton();
        creditLable = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        creditTextArea = new javax.swing.JTextArea();

        creditBack.setText("<< Back");
        creditBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditBackActionPerformed(evt);
            }
        });

        creditLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        creditLable.setText("Credits");

        creditTextArea.setColumns(20);
        creditTextArea.setRows(5);
        creditTextArea.setText("DEVELOPERS\n\nEREN AYTURE\nTANER DÜZCEER\nAHMEY AKİF UĞURTAN\nBERK ATAÇ\n\nDATE 28.03.2018\nVer 1.0");
        jScrollPane2.setViewportView(creditTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creditBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 293, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(creditLable)
                                .addGap(298, 298, 298))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creditLable)
                .addGap(142, 142, 142)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(creditBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void creditBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditBackActionPerformed
        GUIManager.manager.backToMainMenuPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_creditBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creditBack;
    private javax.swing.JLabel creditLable;
    private javax.swing.JTextArea creditTextArea;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
