/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cscrush;

import javax.swing.ImageIcon;

/**
 *
 * @author berka
 */
public class CreditsPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreditsPanel
     */
    public CreditsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        backBC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/creditlgo.gif"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 610, 270, 90);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("DEVELOPERS\n\nEREN AYTURE\nTANER DÜZCEER\nAHMEY AKİF UĞURTAN\nBERK ATAÇ\n\nDATE 28.03.2018\nVer 1.0");
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2);
        jScrollPane2.setBounds(30, 380, 150, 170);

        backBC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back1.png"))); // NOI18N
        backBC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBCMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backBCMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backBCMouseReleased(evt);
            }
        });
        add(backBC);
        backBC.setBounds(590, 610, 43, 41);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/creditlogo.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void backBCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBCMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/back2.png"));
        backBC.setIcon(II);
    }//GEN-LAST:event_backBCMouseEntered

    private void backBCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBCMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/back1.png"));
        backBC.setIcon(II);
    }//GEN-LAST:event_backBCMouseExited

    private void backBCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBCMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/back3.png"));
        backBC.setIcon(II);
    }//GEN-LAST:event_backBCMousePressed

    private void backBCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBCMouseReleased
        GUIManager.manager.backToMainMenuPanel();  
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/back1.png"));
        backBC.setIcon(II);
    }//GEN-LAST:event_backBCMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
