/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cscrush;

import cscrush.AnimationList.AnimationNode;
import java.awt.Dimension;
import javax.swing.JLabel;

/**
 *
 * @author tendoushuu
 */
public class GamePlayScreenPanel extends javax.swing.JPanel {
    
    private GameTable gameTable;
    private BoostersPanel boostersPanel;
    /**
     * Creates new form GamePlayScreenPanel
     */
    public GamePlayScreenPanel() {
        initComponents();
        gameTable = new GameTable( this );
        boostersPanel = new BoostersPanel( this );
        table.add(gameTable);
        boosters.add(boostersPanel);
    }
    
    public void setGameTable(BookCandy[][] tableObjects)
    {
        gameTable.setTableObjects(tableObjects);
    }
    public void altay(){
        GUIManager.manager.powerupaltay();
    }
    public void ozcan(BookCandy[][] tableObjects){
    
    }
    public void eray(int x1,int y1,int x2,int y2){
        GUIManager.manager.poweruperay(x1, y1, x2, y2);
    }
    public void robin(BookCandy[][] tableObjects){
    
    }
    public void william(BookCandy[][] tableObjects){
    
    }
    public void startAnimation(AnimationNode head)
    {
        gameTable.startAnimation(head);
    }
    
    public void setScore(int score)
    {
        currentPoint.setText(""+score);
        validate();
        repaint();
    }
    
    public void setRemainedMove(int score)
    {
        remainedMovePoint.setText(""+score);
        validate();
        repaint();
    }
    
    public void setTargetPoint(String target)
    {
        targetPoint.setText(target);
        validate();
        repaint();
    }
    
    public void setLevelName(int lev)
    {
        levelName.setText("Level " + lev);
        validate();
        repaint();
    }
    
    public void gameOver()
    {
        gameTable.gameOver();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        remainedMovePoint = new javax.swing.JLabel();
        targetPoint = new javax.swing.JLabel();
        currentPoint = new javax.swing.JLabel();
        boosters = new javax.swing.JPanel();
        table = new javax.swing.JPanel();
        levelName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        settingsButton.setText("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Remained Move");

        jLabel2.setText("Target Point");

        jLabel3.setText("Current Point");

        remainedMovePoint.setText("100");

        targetPoint.setText("50000");

        currentPoint.setText("15000");

        boosters.setPreferredSize(new java.awt.Dimension(50, 250));
        boosters.setLayout(new java.awt.GridLayout(1, 0));

        table.setPreferredSize(new java.awt.Dimension(500, 500));
        table.setLayout(new java.awt.GridLayout(1, 0));

        levelName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        levelName.setText("Level 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(settingsButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(remainedMovePoint))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boosters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(targetPoint)
                            .addComponent(currentPoint))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(levelName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(levelName)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(remainedMovePoint)
                                .addGap(57, 57, 57)
                                .addComponent(boosters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton)
                            .addComponent(settingsButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addComponent(targetPoint)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(currentPoint)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        GUIManager.manager.backFromGameScreenPlay();
    }//GEN-LAST:event_backButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
        GUIManager.manager.displaySettings(1);
    }//GEN-LAST:event_settingsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel boosters;
    private javax.swing.JLabel currentPoint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel levelName;
    private javax.swing.JLabel remainedMovePoint;
    private javax.swing.JButton settingsButton;
    private javax.swing.JPanel table;
    private javax.swing.JLabel targetPoint;
    // End of variables declaration//GEN-END:variables
}
