/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cscrush;

import javax.swing.ImageIcon;

/**
 *
 * @author berka
 */
public class HighScorePanel extends javax.swing.JPanel {

    /**
     * Creates new form HighScorePanel
     */
    public HighScorePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        backBH = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("HIGH SCORES");
        add(jLabel1);
        jLabel1.setBounds(190, 80, 340, 60);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        add(jLabel2);
        jLabel2.setBounds(240, 190, 140, 20);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("Score");
        add(jLabel3);
        jLabel3.setBounds(370, 190, 60, 21);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Berk", "Akif", "Taner", "Eren" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(240, 220, 90, 150);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "10456", "9546", "8292", "2365" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        add(jScrollPane3);
        jScrollPane3.setBounds(370, 220, 90, 150);

        backBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back1.png"))); // NOI18N
        backBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBHMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backBHMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backBHMouseReleased(evt);
            }
        });
        add(backBH);
        backBH.setBounds(0, 590, 43, 41);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Open-Book-Backgrounds.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(-100, 0, 770, 670);
    }// </editor-fold>//GEN-END:initComponents

    private void backBHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBHMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/back2.png"));
        backBH.setIcon(II);
    }//GEN-LAST:event_backBHMouseEntered

    private void backBHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBHMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/back1.png"));
        backBH.setIcon(II);
    }//GEN-LAST:event_backBHMouseExited

    private void backBHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBHMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/back3.png"));
        backBH.setIcon(II);
    }//GEN-LAST:event_backBHMousePressed

    private void backBHMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBHMouseReleased
        GUIManager.manager.backToMainMenuPanel();
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/back1.png"));
        backBH.setIcon(II);
    }//GEN-LAST:event_backBHMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
