/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cscrush;

import javax.swing.ImageIcon;

/**
 *
 * @author tendoushuu
 */
public class MainMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuPanel
     */
    public MainMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        set1 = new javax.swing.JLabel();
        playb = new javax.swing.JLabel();
        infoB = new javax.swing.JLabel();
        creditsB = new javax.swing.JLabel();
        highsB = new javax.swing.JLabel();
        exitB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(664, 670));
        setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(380, 350, 320, 350);

        set1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/set1.png"))); // NOI18N
        set1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                set1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                set1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                set1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                set1MouseReleased(evt);
            }
        });
        add(set1);
        set1.setBounds(140, 165, 150, 51);

        playb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/play1.png"))); // NOI18N
        playb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playbMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                playbMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                playbMouseReleased(evt);
            }
        });
        add(playb);
        playb.setBounds(310, 253, 96, 96);

        infoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info1.png"))); // NOI18N
        infoB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                infoBMouseReleased(evt);
            }
        });
        add(infoB);
        infoB.setBounds(415, 165, 149, 51);

        creditsB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/credits1.png"))); // NOI18N
        creditsB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creditsBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creditsBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                creditsBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                creditsBMouseReleased(evt);
            }
        });
        add(creditsB);
        creditsB.setBounds(56, 302, 149, 47);

        highsB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/high1.png"))); // NOI18N
        highsB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                highsBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                highsBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                highsBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                highsBMouseReleased(evt);
            }
        });
        add(highsB);
        highsB.setBounds(500, 301, 150, 48);

        exitB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ext1.png"))); // NOI18N
        exitB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitBMouseReleased(evt);
            }
        });
        add(exitB);
        exitB.setBounds(282, 422, 149, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cscrush.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(201, 46, 313, 44);
    }// </editor-fold>//GEN-END:initComponents

    private void set1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set1MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/set2.png"));
        set1.setIcon(II);
    }//GEN-LAST:event_set1MouseEntered

    private void set1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set1MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/set1.png"));
        set1.setIcon(II);
    }//GEN-LAST:event_set1MouseExited

    private void set1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set1MousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/set3.png"));
        set1.setIcon(II);        // TODO add your handling code here:
    }//GEN-LAST:event_set1MousePressed

    private void set1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set1MouseReleased
        GUIManager.manager.displaySettings(0);  
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/set1.png"));
        set1.setIcon(II);
    }//GEN-LAST:event_set1MouseReleased

    private void playbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playbMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/play2.png"));
        playb.setIcon(II);           // TODO add your handling code here:
    }//GEN-LAST:event_playbMouseEntered

    private void playbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playbMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/play1.png"));
        playb.setIcon(II);        // TODO add your handling code here:
    }//GEN-LAST:event_playbMouseExited

    private void playbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playbMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/play3.png"));
        playb.setIcon(II);        // TODO add your handling code here:
    }//GEN-LAST:event_playbMousePressed

    private void playbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playbMouseReleased
        GUIManager.manager.displayLevels();
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/play1.png"));
        playb.setIcon(II);         
    }//GEN-LAST:event_playbMouseReleased

    private void infoBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/info2.png"));
        infoB.setIcon(II); 
    }//GEN-LAST:event_infoBMouseEntered

    private void infoBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/info1.png"));
        infoB.setIcon(II); 
    }//GEN-LAST:event_infoBMouseExited

    private void infoBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/info3.png"));
        infoB.setIcon(II); 
    }//GEN-LAST:event_infoBMousePressed

    private void infoBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBMouseReleased
        GUIManager.manager.displayHelp();
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/info1.png"));
        infoB.setIcon(II); 
    }//GEN-LAST:event_infoBMouseReleased

    private void creditsBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsBMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/credits2.png"));
        creditsB.setIcon(II);
    }//GEN-LAST:event_creditsBMouseEntered

    private void creditsBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsBMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/credits1.png"));
        creditsB.setIcon(II);
    }//GEN-LAST:event_creditsBMouseExited

    private void creditsBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsBMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/credits3.png"));
        creditsB.setIcon(II);
    }//GEN-LAST:event_creditsBMousePressed

    private void creditsBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsBMouseReleased
        GUIManager.manager.displayCredits();
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/credits1.png"));
        creditsB.setIcon(II);
    }//GEN-LAST:event_creditsBMouseReleased

    private void highsBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highsBMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/high2.png"));
        highsB.setIcon(II);
    }//GEN-LAST:event_highsBMouseEntered

    private void highsBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highsBMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/high1.png"));
        highsB.setIcon(II);
    }//GEN-LAST:event_highsBMouseExited

    private void highsBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highsBMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/high3.png"));
        highsB.setIcon(II);
    }//GEN-LAST:event_highsBMousePressed

    private void highsBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highsBMouseReleased
        GUIManager.manager.displayHighScores();
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/high1.png"));
        highsB.setIcon(II);
    }//GEN-LAST:event_highsBMouseReleased

    private void exitBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/ext2.png"));
        exitB.setIcon(II);
    }//GEN-LAST:event_exitBMouseEntered

    private void exitBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/ext1.png"));
        exitB.setIcon(II);
    }//GEN-LAST:event_exitBMouseExited

    private void exitBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/icons/ext3.png"));
        exitB.setIcon(II);
    }//GEN-LAST:event_exitBMousePressed

    private void exitBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseReleased
        GUIManager.manager.exitGame();
    }//GEN-LAST:event_exitBMouseReleased
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creditsB;
    private javax.swing.JLabel exitB;
    private javax.swing.JLabel highsB;
    private javax.swing.JLabel infoB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel playb;
    private javax.swing.JLabel set1;
    // End of variables declaration//GEN-END:variables
}
