/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cscrush;

/**
 *
 * @author berka
 */
public class SettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soundOnOff = new javax.swing.JToggleButton();
        settLabel = new javax.swing.JLabel();
        settBack = new javax.swing.JButton();
        settLogOut = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(664, 670));

        soundOnOff.setText("Sound On/Off");
        soundOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundOnOffActionPerformed(evt);
            }
        });

        settLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        settLabel.setText("SETTINGS");

        settBack.setText("<< Back");
        settBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settBackActionPerformed(evt);
            }
        });

        settLogOut.setText("Logout");
        settLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(273, 273, 273)
                            .addComponent(settLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(settLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(settBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(soundOnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settLabel)
                .addGap(157, 157, 157)
                .addComponent(soundOnOff)
                .addGap(31, 31, 31)
                .addComponent(settLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                .addComponent(settBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void soundOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundOnOffActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_soundOnOffActionPerformed

    private void settBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settBackActionPerformed
        GUIManager.manager.backToMainMenuPanel();      // TODO add your handling code here:
    }//GEN-LAST:event_settBackActionPerformed

    private void settLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settLogOutActionPerformed

        GUIManager.manager.backToLoginPanel();
    }//GEN-LAST:event_settLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton settBack;
    private javax.swing.JLabel settLabel;
    private javax.swing.JButton settLogOut;
    private javax.swing.JToggleButton soundOnOff;
    // End of variables declaration//GEN-END:variables
}
